name: form_generator
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.2+1
  flutter_localizations:
    sdk: flutter
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  google_fonts: ^3.0.0
  hemend:
    git:
      url: https://github.com/FMotalleb/hemend_base
  http: ^0.13.4
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0
  path_provider: ^2.0.10
  intl: ^0.17.0
dev_dependencies:
  sqflite_common_ffi: ^2.1.1
  bloc_test: ^9.0.3
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^2.5.0
  mockito: ^5.1.0
flutter_intl:
  main_locale: en_US
  enabled: true

flutter:
  generate: true
  uses-material-design: true
