name: form_generator
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.0
  hemend:
    git:
      url: https://github.com/FMotalleb/hemend_base
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  isar: 3.0.0-dev.4
  isar_flutter_libs: 3.0.0-dev.4
  path_provider: ^2.0.10
  sqflite: ^2.0.2+1
dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  isar_generator: 3.0.0-dev.4
  mockito: ^5.1.0
  sqflite_common_ffi: ^2.1.1
  ffi: 1.2.1
dependency_overrides:
  ffi: 2.0.1
flutter_intl:
  main_locale: en_US
  enabled: true

flutter:
  generate: true
  uses-material-design: true
