# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: unit_tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
          channel: "stable"
      - run: mkdir .dart_tool/
      - run: mkdir .dart_tool/flutter_gen/
      - run: echo dependencies:& > .dart_tool/flutter_gen/pubspec.yaml
      - run: cat .dart_tool/flutter_gen/pubspec.yaml
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter test
